services:
  palworld-server:
    # https://github.com/pocketpairjp/palworld-dedicated-server-docker/pkgs/container/palserver
    image: ghcr.io/pocketpairjp/palserver:v1.0.3.101283
    container_name: palworld-server
    network_mode: host #"container:wg-portal"
    entrypoint: /pal/entrypoint.sh


    restart: unless-stopped

    # https://tech.palworldgame.com/settings-and-operation/arguments
    command:
      - -port=8211
      - -useperfthreads
      - -NoAsyncLoadingThread
      - -UseMultithreadForDS

   # ports:
   #   - "8211:8211/udp"
    volumes:
      - ./scripts/entrypoint.sh:/pal/entrypoint.sh:ro
      - ./saved:/pal/Package/Pal/Saved
      - ./defaults:/pal/defaults

  pal-manager:
    image: bananums/pal-manager:dev #Dev to test, pin version after stabilizing/release
    environment:
      - PAL_LISTEN=127.0.0.1:8080
      - PAL_SETTINGS=/data/live/PalWorldSettings.ini
      - PAL_DEFAULTS=/data/defaults/DefaultPalWorldSettings.ini
      - PAL_REST=http://127.0.0.1:8212/v1/api
    volumes:
      - ./saved/Config/LinuxServer:/data/live
      - ./defaults:/data/defaults:ro
